[package]
name = "tag_splitter"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
chrono = "0.4.41"
clap = { version = "4.5.45", features = ["derive"] }
indexmap = "2.10.0"
num_cpus = "1.17.0"
rust-htslib = "0.50.0"
